---
title: "Two_stage_2.0"
author: "Anna Boser"
date: "7/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

library(cvTools)
library(dplyr)
library(tidyr)
library(lme4)
library(spgwr)
library(leaps)
library(sp)
# library(GWmodel)
library(here)
```


#Apply model to full grid
```{r}
Data <- read.csv(file = here::here("Data", "Train.csv"))
Data$Day <- as.factor(Data$Day)
Data <- filter(Data, !is.na(BLH))
w_AOD <- filter(Data, !is.na(AOD)) #1
# wo_AOD <- filter(Data, is.na(AOD)) 
# wo_AOD$AOD <- 0
indfunc <- function(val){
  if (is.na(val)){
    return(0)
  } else {
    return(1)
  }
}
ind_AOD <- Data
ind_AOD$AOD <- unlist(lapply(ind_AOD$AOD, indfunc)) #3

Grid <- read.csv(file = here("Data", "Full.csv")) #missing BLH already removed
Grid_w_AOD <- filter(Grid, !is.na(AOD), Day %in% c(274, 286, 304)) #2
Grid_wo_AOD <- filter(Grid, is.na(AOD), Day %in% c(274, 286, 304)) #4
Grid_wo_AOD$AOD <- 0
rm(Grid)
```

```{r LME_formula}
LME_formula <- "PM ~ Elevation + 
                      Emissions +
                      Forest +
                      Streets +
                      Plumes_High +
                      Plumes_Med +
                      Plumes_Low +
                      Max_Temp +
                      Max_Wind +
                      Rel_Humidity +
                      BLH +
                      AOD +
                      (1 + 
                         Plumes_High +
                      Plumes_Med +
                      Plumes_Low +
                      Max_Temp +
                      Max_Wind +
                      Rel_Humidity +
                      BLH +
                      AOD| Day)"
```

```{r}
GWR_formula <- "resid ~ AOD"
```

Training the model
```{r}
Fit_to_grid <- function(lme_formula, gwr_formula, train_AOD, train_wo_AOD, test_AOD, test_wo_AOD, bw = NA){
# The way the two-stage model is broken down: 
  # 1: use the training data to fit a linear mixed effects model
  # 2: using the training data, predict the PM using the LME and calculate the residuals
  # 3: use the training data residuals to fit the GWR model on the residuals (actual - predicted) from the LME model
  # 4: use the test data to predict the PM with the LME model and the residuals from the LME model using the GWR model
  # 5: add the gwr-predicted residuals to the lme-predicted PM values to obtain the final prediction. 
  
  test_AOD <- filter(test_AOD, Day %in% unique(train_AOD$Day)) #october 1, 13, and 31
  test_wo_AOD <- filter(test_wo_AOD, Day %in% unique(train_wo_AOD$Day))
  
  # 1:
  AOD_lme <- lmer(formula = lme_formula, 
                 data = train_AOD)
  wo_AOD_lme <- lmer(formula = lme_formula, 
                 data = train_wo_AOD)
  
  print("LME trained")
  
  # 2:
  train_AOD$resid <- train_AOD$PM - predict(AOD_lme) #training residuals
  AOD_lme_predictions <- predict(AOD_lme, newdata = test_AOD) #testing predictions
  
  train_wo_AOD$resid <- train_wo_AOD$PM - predict(wo_AOD_lme) #training residuals
  wo_AOD_lme_predictions <- predict(wo_AOD_lme, newdata = test_wo_AOD) #testing predictions
  
  print("LME predictions and residuals calculated")
  
  # 3 and 4: 
  
  #convert train and test data to sp for easier use in spgwr
  train_sp_AOD <- SpatialPointsDataFrame(coords = cbind(train_AOD$Lon, train_AOD$Lat), data = train_AOD, proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
  test_sp_AOD <- SpatialPointsDataFrame(coords = cbind(test_AOD$Lon, test_AOD$Lat), data = test_AOD, proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
  
  train_sp_wo_AOD <- SpatialPointsDataFrame(coords = cbind(train_wo_AOD$Lon, train_wo_AOD$Lat), data = train_wo_AOD, proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
  test_sp_wo_AOD <- SpatialPointsDataFrame(coords = cbind(test_wo_AOD$Lon, test_wo_AOD$Lat), data = test_wo_AOD, proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
  
  print("Data converted to sp objects")
  
  if (is.na(bw)){
    gwr.bw.AOD <- gwr.sel(gwr_formula, data = train_sp_AOD, longlat = TRUE)
    gwr_model_AOD <- gwr(gwr_formula, data = train_sp_AOD, bandwidth = gwr.bw.AOD, longlat = TRUE, fit.points = test_sp_AOD, predictions = TRUE)
  
    gwr.bw.wo.AOD <- gwr.sel(gwr_formula, data = train_sp_wo_AOD, longlat = TRUE)
    gwr_model_wo_AOD <- gwr(gwr_formula, data = train_sp_wo_AOD, bandwidth = gwr.bw.wo.AOD, longlat = TRUE, fit.points = test_sp_wo_AOD, predictions = TRUE)
  } else {
    gwr_model_AOD <- gwr(gwr_formula, data = train_sp_AOD, bandwidth = bw, longlat = TRUE, fit.points = test_sp_AOD, predictions = TRUE)
    
    gwr_model_wo_AOD <- gwr(gwr_formula, data = train_sp_wo_AOD, bandwidth = bw, longlat = TRUE, fit.points = test_sp_wo_AOD, predictions = TRUE)
  }

  print("GWR model finished")
  
  gwr_resid_AOD <- gwr_model_AOD$SDF$pred
  gwr_resid_wo_AOD <- gwr_model_wo_AOD$SDF$pred
  
  AOD_test_predictions <- gwr_resid_AOD + AOD_lme_predictions
  wo_AOD_test_predictions <- gwr_resid_wo_AOD + wo_AOD_lme_predictions
  
  test_AOD$stage_2 <- gwr_resid_AOD #save the modeled residuals from the second stage
  test_wo_AOD$stage_2 <- gwr_resid_wo_AOD 
  
  test_AOD$pred <- AOD_test_predictions
  test_wo_AOD$pred <- wo_AOD_test_predictions
  
  print("predictions calculated")
  
  full_grid <- rbind(test_AOD, test_wo_AOD)
  full_grid <- arrange(full_grid, Id, Day)
  full_grid <- select(full_grid, Id, Day, pred)
  full_grid <- pivot_wider(full_grid, names_from = Day, names_prefix = "Day", values_from = "pred")
  
  stage2 <- rbind(test_AOD, test_wo_AOD)
  stage2 <- arrange(stage2, Id, Day)
  stage2 <- select(stage2, Id, Day, stage_2)
  stage2 <- pivot_wider(stage2, names_from = Day, names_prefix = "Day", values_from = "stage_2")
  
  return(list(full_grid, stage2)) #return grid of both final values and the modeled residuals from the second stage
}
```

```{r}
start_time = Sys.time()
Full_grid <- Fit_to_grid(lme_formula = LME_formula, gwr_formula = GWR_formula, train_AOD = w_AOD, train_wo_AOD = ind_AOD, test_AOD = Grid_w_AOD, test_wo_AOD = Grid_wo_AOD, bw = NA)
end_time <-  Sys.time()
end_time - start_time
```

```{r}
write.csv(Full_grid[1], file = here::here("Results", "Grid", "GWR_Full_Grid.csv"), row.names = FALSE)
write.csv(Full_grid[2], file = here::here("Results", "Grid", "GWR_Second_stage.csv"), row.names = FALSE)
```
